composer.json
composer.lock
symfony.lock

In order to model our application
For developers
We need phpspec in the project
Reviewing: please note that few commits are connected to previous PR, last 3 commits are related to this PR.
Closes #3

Add phpspec

---

.php_cs.dist
composer.json
composer.lock
phpcs.xml
phpmd.xml
phpstan.neon
symfony.lock

In order to keep code quality good,
we should add php-cs-fixer, php_codesniffer, php_messdetector & phpstan
Closes #7

Add code quality tools

---

.gitignore

Add some more files/folders to be ignored

---

build.xml
circle.yml
tests/bootstrap.php

Add configuration file to run CircleCI
Closes #8

Add CircleCI

---

circle.yml

I'm trying out https://twistapp.com/, to connect CircleCI with TwistApp, we need to add a webhook.
Closes #15

CircleCI: Notify Twist

---

.gitignore
composer.json
composer.lock
symfony.lock

In order to write tests
As maintainers
We need phpunit to be added to project as a dev dependency
Closes #34

Add phpunit

---

spec/Organization/Controller/OrganizationControllerSpec.php
spec/Organization/Entity/OrganizationEntitySpec.php
src/Organization/Controller/OrganizationController.php
src/Organization/Entity/OrganizationEntity.php

Part of [Organization modeling](https://github.com/NullTraining/reviewz/issues/18):
This will add a basic Organization model:
- title
- description
- founder
and OrganizationController:
- create a new Organization

#18 - Organization modeling

---

.gitignore
README.md
Vagrantfile
vagrant/config/.gitignore
vagrant/config/vagrant-local.example.yml
vagrant/nginx/app.conf
vagrant/nginx/log/.gitignore
vagrant/provision/always-as-root.sh
vagrant/provision/once-as-root.sh
vagrant/provision/once-as-vagrant.sh

For those of us that use Windows machines (like me) added vagrant for easier development proccess.
Setup procedures added to README.md

Vagrant setup

---

spec/Organization/Controller/ClaimControllerSpec.php
src/Organization/Controller/ClaimController.php
src/Talk/Entity/TalkEntity.php

Speakers can only claim talks that have no speaker set yet.
Part of #25

Claiming a talk

---

spec/Organization/Controller/OrganizationControllerSpec.php
spec/Organization/Entity/OrganizationEntitySpec.php
src/Organization/Controller/OrganizationController.php
src/Organization/Entity/OrganizationEntity.php

This will add approval state to OrganizationEntity, with `approve` and `disapprove` methods for setting state, and `isApproved` method for checking entity approval status.

Issue #20 - Approve Organization

---

spec/Organization/Controller/RsvpControllerSpec.php
spec/Organization/Entity/MeetupEntitySpec.php
src/Organization/Controller/RsvpController.php
src/Organization/Entity/MeetupEntity.php
src/Organization/Entity/OrganizationEntity.php

Members can RSVP `Yes` or `No` to a meetup.
Part of #24

RSVP to event

---

spec/Geo/Entity/CityEntitySpec.php
spec/Geo/Entity/CountryEntitySpec.php
spec/Geo/Entity/LocationEntitySpec.php
src/Geo/Entity/CityEntity.php
src/Geo/Entity/CountryEntity.php
src/Geo/Entity/LocationEntity.php

In order for organizations to have a hometown, meetups to have a location, users to be from a city we need to add support for location,city & country. 
This is just the base setup, far away from all done
Part of #47

Add Country, City & Location

---

spec/Talk/Entity/FeedbackEntitySpec.php
src/Talk/Entity/FeedbackEntity.php

#29 Add Feedback entity

---

spec/Event/Controller/EventControllerSpec.php
spec/Event/Entity/EventEntitySpec.php
src/Event/Controller/EventController.php
src/Event/Entity/EventEntity.php
src/Organization/Entity/OrganizationEntity.php

added modeling for creating an event

Issue 21 event creating

---

spec/Organization/Controller/OrganizationControllerSpec.php
spec/Organization/Entity/OrganizationEntitySpec.php
spec/Organization/Repository/OrganizationRepositorySpec.php
spec/User/Entity/UserEntitySpec.php
src/Organization/Controller/OrganizationController.php
src/Organization/Entity/OrganizationEntity.php
src/Organization/Repository/OrganizationRepository.php
src/User/Entity/UserEntity.php

~~# WIP.~~
Part of [User joins an Organization](https://github.com/NullTraining/reviewz/issues/19):
User can join an organization, and it needs to hold a reference to the organization joined.
Since this is a two-way relation, Organization needs to keep track of its members, so it holds a reference to the User.
Started work on OrganizationController, but things got a bit complicated, because OrganizationRepository and EntityManager came to play.

#19 - User joins an Organization

---

spec/Event/Controller/EventControllerSpec.php
spec/Event/Entity/EventEntitySpec.php
src/Event/Controller/EventController.php
src/Event/Entity/EventEntity.php

Added location to event, because, I think, events should have location

Issue 21 event location

---

spec/Talk/Controller/TalkControllerSpec.php
src/Talk/Controller/TalkController.php

Organizers should be able to create talk for event.
Closes #22

Organizer can add a talk

---

features/managing-new-organizations.feature
src/Organization/Behat/OrganizationDomainContext.php

Admins can reject organizations
Part of #20

Rejecting new organization

---

src/User/Entity/UserEntity.php

Just simple addition of property "phoneNumber"
Closes #68

Add phoneNumber property to user.

---

behat.yml.dist
features/organizer-can-create-event.feature
phpstan.neon
src/Event/Behat/EventDomainContext.php
src/Organization/Entity/OrganizationEntity.php

Implemented getEvents and addEvent on OrganizationEntity
Added feature test
#21

Feature organizer can create event

---

features/join-organization.feature
src/Organization/Entity/OrganizationEntity.php
src/User/Behat/UserDomainContext.php

In order to attend events, users must be able to join an organization
Closes #82

Join organization

---

phpstan.neon
spec/User/Entity/UserEntitySpec.php
spec/User/Entity/UserIdSpec.php
src/Event/Behat/EventDomainContext.php
src/Talk/Behat/TalkDomainContext.php
src/User/Behat/UserDomainContext.php
src/User/Entity/UserEntity.php
src/User/Entity/UserId.php

As we are going with commands & handlers, we need to have UserId predefined

Define and use UserId

---

features/rsvp-to-event.feature
src/Event/Behat/EventDomainContext.php
src/Event/Entity/EventEntity.php
src/Organization/Entity/OrganizationEntity.php

This PR is adding bit of support on attending/not coming to an event.
I would suggest reviewing commit-by-commit, but please skip first 2 as they are part of #85.
Closes #83
NoteToMyself: rebase after #85 is merged

Feature: RSVP to event

---

src/Event/Behat/EventDomainContext.php

I have merged older PR's with incompatible changes (missing UserId) so master is now broken :(

BUGFIX: Users being created in EventDomainContext are missing UserId :(

---

composer.json
composer.lock
config/bundles.php
src/Event/Behat/EventDomainContext.php
symfony.lock

It adds simplebus + integration with Symfony
Closes #92

Add simplebus

---

behat.yml.dist
composer.json
features/user-registration.feature
spec/User/Command/RegisterUserSpec.php
spec/User/Hander/UserRegistrationHandlerSpec.php
src/Geo/Repository/CityRepository.php
src/User/Behat/UserApplicationContext.php
src/User/Behat/UserDomainContext.php
src/User/Command/RegisterUser.php
src/User/Entity/UserEntity.php
src/User/Hander/UserRegistrationHandler.php
src/User/Repository/UserRepository.php
tests/Geo/Repository/CityInMemoryRepository.php
tests/User/Repository/UserInMemoryRepository.php

In order to register users we need to define application layer for it using command pattern.
Pull request should be commit-by-commit review friendly.
Closes #94

User application layer: user registration

---

features/organizer-can-create-event.feature
src/Event/Behat/EventDomainContext.php

This is based on PR #75 by @flackovic 
I rearranged and renamed some scenarios and methods.
In order to complete this, we need to implement spec and code for whatever will be the outcome of the poll in #76

Feature #21 [Behat] Organizers Can Create New Events

---

phpstan.neon
spec/Organization/Entity/OrganizationEntitySpec.php
src/Event/Behat/EventDomainContext.php
src/Organization/Behat/OrganizationDomainContext.php
src/Organization/Controller/OrganizationController.php
src/Organization/Entity/OrganizationEntity.php
src/Organization/Entity/OrganizationId.php
src/Talk/Behat/TalkDomainContext.php
src/User/Behat/UserDomainContext.php

In order for users to join an organization, organization has to have an ID
Part of #101

Add OrganizationId

---

behat.yml.dist
src/Event/Behat/EventDomainContext.php
src/Talk/Behat/TalkDomainContext.php
src/User/Behat/UserApplicationContext.php
src/User/Behat/UserDomainContext.php
src/User/Behat/UserFixturesContext.php

In order to keep user details across different contexts easily managable we should keep them in one place and add the context to each suite

Add UserFixturesContext

---

src/App/CommandBus.php

BUGFIX: By mistake, CommandBus was extending wrong class :(

---

phpstan.neon
src/Talk/Behat/TalkApplicationContext.php

As 2 PR's got merged at same time, master broke with expectations

BUGFIX: Missing organization argument

---

behat.yml.dist
features/create-organization.feature
spec/Organization/Command/CreateOrganizationCommandSpec.php
spec/Organization/Handler/CreateOrganizationHandlerSpec.php
src/Organization/Behat/OrganizationApplicationContext.php
src/Organization/Command/CreateOrganizationCommand.php
src/Organization/Handler/CreateOrganizationHandler.php

- Added Create Organization Application context, command and handler
- Handled first scenario

Issue 114 org app context

---

behat.yml.dist
spec/Organization/Command/CreateOrganizationCommandSpec.php
spec/Organization/Handler/CreateOrganizationHandlerSpec.php
src/Organization/Behat/OrganizationApplicationContext.php
src/Organization/Command/CreateOrganizationCommand.php
src/Organization/Handler/CreateOrganizationHandler.php

There were few issues introduced to OrganizationApplicationContext as it was built in paralle to other things and got outdated

Bugfixes on OrganizationApplicationContext

---

behat.yml.dist
features/create-organization.feature
features/managing-new-organizations.feature
spec/Organization/Command/ApproveOrganizationCommandSpec.php
spec/Organization/Command/RejectOrganizationCommandSpec.php
spec/Organization/Handler/ApproveOrganizationHandlerSpec.php
spec/Organization/Handler/RejectOrganizationHandlerSpec.php
src/Organization/Behat/OrganizationApplicationContext.php
src/Organization/Command/ApproveOrganizationCommand.php
src/Organization/Command/RejectOrganizationCommand.php
src/Organization/Handler/ApproveOrganizationHandler.php
src/Organization/Handler/RejectOrganizationHandler.php
src/User/Behat/UserFixturesContext.php

This PR includes fixes from #135 (first 3 commits in this PR).
Rest of the organization based scenarios are now implemented on app layer as well, I'we tried to keep them in 1-scenario is 1-commit so it should be commit-by-commit review friendly.
Closes #114

Finishing up organization application layer

---

behat.yml.dist
features/organizer-marks-user-attendance.feature
src/Event/Behat/EventDomainContext.php

UPDATE:
Implemented missing scenarios and steps.
We **really** should consider refactoring the context files. 
~Completed the EventDomainContext, need to finish up other contexts
marked with `@event` tag~
~I'm having problems grasping the scope of contexts and their separation and would appreciate some help with it.~
~Tagging @msvrtan for help, please :question:~ 
In reference to #79

Organizer manages user attendance

---

composer.json
composer.lock

New version of phpstan is out!
This PR incorporates changes from #175 so please check only last commits!

Upgrade phpstan to 0.10

---

behat.yml.dist
features/organizer-marks-user-attendance.feature
features/rsvp-to-event.feature
spec/Event/Command/MarkUserAsAttendedSpec.php
spec/Event/Handler/MemberAttendanceHandlerSpec.php
src/Event/Behat/EventApplicationContext.php
src/Event/Behat/EventDomainContext.php
src/Event/Command/MarkUserAsAttended.php
src/Event/Command/RsvpNo.php
src/Event/Command/RsvpYes.php
src/Event/Handler/MemberAttendanceHandler.php
src/Event/Handler/RsvpNoHandler.php
src/Event/Handler/RsvpYesHandler.php
src/Event/Repository/EventRepository.php
tests/Event/Repository/EventInMemoryRepository.php

Added event application context

Added application layer for events

---

src/Event/Behat/EventDomainContext.php
src/Organization/Behat/OrganizationFixturesContext.php

We decided for now we will be using only NY dev ninjas organization so having "Local organization" in fixtures just creates confusion

Remove "Local organization" from fixtures

---

features/managing-organization-organizers.feature
spec/Organization/Command/PromoteOrganizerCommandSpec.php
spec/Organization/Entity/OrganizationEntitySpec.php
spec/Organization/Handler/PromoteOrganizerHandlerSpec.php
src/Organization/Behat/OrganizationApplicationContext.php
src/Organization/Behat/OrganizationDomainContext.php
src/Organization/Command/PromoteOrganizerCommand.php
src/Organization/Entity/OrganizationEntity.php
src/Organization/Exception/AlreadyAnOrganizerException.php
src/Organization/Exception/AlreadyMemberException.php
src/Organization/Exception/CantPromoteUserThatIsNotMemberOfOrganizationException.php
src/Organization/Handler/PromoteOrganizerHandler.php

In order to allow promoting existing member to an organizer, we need to support this feature
Key difference between adding an organizer and promoting is that for promotion, we expect user to already be a member!
Closes #137

Promoting member to organizer

---

features/organizer-can-create-event.feature
spec/Event/Command/CreateEventSpec.php
spec/Event/Handler/CreateEventHandlerSpec.php
src/Event/Behat/EventApplicationContext.php
src/Event/Behat/EventDomainContext.php
src/Event/Command/CreateEvent.php
src/Event/Handler/CreateEventHandler.php
src/Geo/Repository/LocationRepository.php
src/Organization/Exception/UserNotOrganizerException.php
tests/Location/Repository/LocationInMemoryRepository.php

There was a bug in the feature file for Event Application Context which
was a false positive - user who was not an organization organizer was
able to create a new event for organization.
Closes #181

[Behat/app context] Check if current user is organizer #181
